package com.angel.api.dto;

import com.angel.model.Activity;
import java.time.LocalDateTime;

/**
 * Data Transfer Object pour représenter une activité venant de l'API Angel-server-capture.
 */
public class ActivityDTO {

    private String activityType;
    private long timestamp;
    private double confidence;
    private String source; // "video", "audio", "combined", etc.
    private String additionalInfo;
    private Activity activity; // Référence vers l'enum Activity

    // Constructeur par défaut pour la désérialisation JSON
    public ActivityDTO() {
    }

    /**
     * Constructeur avec tous les paramètres.
     * 
     * @param activityType Type d'activité détectée
     * @param timestamp Timestamp de la détection (en millisecondes depuis l'epoch)
     * @param confidence Niveau de confiance de la détection (0.0 à 1.0)
     * @param source Source de la détection (vidéo, audio, combiné, etc.)
     * @param additionalInfo Informations supplémentaires éventuelles
     */
    public ActivityDTO(String activityType, long timestamp, double confidence, String source, String additionalInfo) {
        this.activityType = activityType;
        this.timestamp = timestamp;
        this.confidence = confidence;
        this.source = source;
        this.additionalInfo = additionalInfo;
        // Tenter de convertir le string en enum Activity
        try {
            this.activity = Activity.valueOf(activityType.toUpperCase());
        } catch (IllegalArgumentException e) {
            this.activity = null;
        }
    }
    
    /**
     * Constructeur avec Activity enum (pour compatibilité avec TestDataGenerator).
     */
    public ActivityDTO(Activity activity, double confidence, long timestamp) {
        this.activity = activity;
        this.activityType = activity != null ? activity.name() : "UNKNOWN";
        this.confidence = confidence;
        this.timestamp = timestamp;
        this.source = "test"; // Source par défaut pour les tests
        this.additionalInfo = "Generated by test simulator";
    }

    // Getters et setters
    public String getActivityType() {
        return activityType;
    }

    public void setActivityType(String activityType) {
        this.activityType = activityType;
        // Mettre à jour l'enum Activity correspondant
        try {
            this.activity = Activity.valueOf(activityType.toUpperCase());
        } catch (IllegalArgumentException e) {
            this.activity = null;
        }
    }

    public long getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(long timestamp) {
        this.timestamp = timestamp;
    }

    public double getConfidence() {
        return confidence;
    }

    public void setConfidence(double confidence) {
        this.confidence = confidence;
    }

    public String getSource() {
        return source;
    }

    public void setSource(String source) {
        this.source = source;
    }

    public String getAdditionalInfo() {
        return additionalInfo;
    }

    public void setAdditionalInfo(String additionalInfo) {
        this.additionalInfo = additionalInfo;
    }
    
    /**
     * Récupère l'enum Activity associé.
     */
    public Activity getActivity() {
        return activity;
    }
    
    /**
     * Définit l'enum Activity associé.
     */
    public void setActivity(Activity activity) {
        this.activity = activity;
        this.activityType = activity != null ? activity.name() : "UNKNOWN";
    }

    /**
     * Convertit le timestamp en objet LocalDateTime.
     * 
     * @return LocalDateTime correspondant au timestamp
     */
    public LocalDateTime getDateTime() {
        return LocalDateTime.ofInstant(
            java.time.Instant.ofEpochMilli(timestamp), 
            java.time.ZoneId.systemDefault()
        );
    }

    @Override
    public String toString() {
        return "ActivityDTO{" +
                "activityType='" + activityType + '\'' +
                ", timestamp=" + timestamp +
                ", confidence=" + confidence +
                ", source='" + source + '\'' +
                ", additionalInfo='" + additionalInfo + '\'' +
                ", activity=" + activity +
                '}';
    }
}